name: ko-built saveweb Images

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/saveweb-go.yml'
  schedule:
  - cron: "20 * * * *"
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/saveweb

jobs:
  ko-build-images:
    name: build images with ko-build
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch the latest tag
        shell: bash
        run: |
          curl() { $(type -P curl) -LRq --retry 5 --retry-delay 10 --retry-max-time 60 --fail "$@"; }

          cnblogs_repo='git.saveweb.org/saveweb/cnblogs'
          cnblogs_latest_tag=$(curl -L -- "https://${cnblogs_repo}/tags/list" \
              | jq -r .results[] | sort -Vr | head -n 1)

          for _var in cnblogs_latest_tag; do
              if [[ -z "${!_var}" ]]; then
                  echo "FATAL: ${_var} is empty!"
                  exit 1
              fi
              echo "${_var}=${!_var}" >> "$GITHUB_ENV"
          done
          echo "cnblogs_repo=${cnblogs_repo}" >> "$GITHUB_ENV"

          curl -o '.ko.yaml' -- \
              https://raw.githubusercontent.com/saveweb/saveweb-images/master/prod.ko.yaml

      - name: Clone the git repos
        shell: bash
        run: |
          git clone -j "$(nproc)" \
              --no-tags --shallow-submodules --recurse-submodules --depth 1 --single-branch \
              --branch "$cnblogs_latest_tag" \
              "https://${cnblogs_repo}.git"
          cp .ko.yaml ./cnblogs/

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ko-build/setup-ko@v0.7
        env:
          KO_DOCKER_REPO: docker.io/${{ env.REGISTRY_IMAGE }}
        with:
          version: tip

      # TODO: issue the ko-build commands in parallel, while keeping the ko command from been installed for several times
      - run: ko build ./cmd/... --platform=linux/amd64,linux/arm64 --bare --tags 'cnblogs'
        working-directory: ./cnblogs
      - run: |
          rm -f ./.ko.yaml
          ko build ./cmd/... --platform=linux/amd64,linux/arm64 --bare --tags 'cnblogs-debug' --debug
        working-directory: ./cnblogs
